version: 0.0
os: linux
files:
  - source: / # The source directory in your revision (S3, Git, etc.)
    destination: /var/www/html # Destination on the EC2 instance

permissions:
  - object: /var/www/html
    owner: www-data
    group: www-data
    mode: 755
    type:
      - file
      - directory

hooks:
  BeforeInstall:
    - location: /before_install.sh
      timeout: 300
      runas: root

  AfterInstall:
    - location: /apache_configure_script.sh
      timeout: 300
      runas: root

  ApplicationStart:
    - location: /start_server.sh
      timeout: 300
      runas: root

  ValidateService:
    - location: /validate_service.sh
      timeout: 300
      runas: root
