---
version: 0.2
phases:
  install:
    runtime-versions:
      php: 8.2
    commands:
      - echo Updating package index...
      - sudo apt-get update -y
      - echo Installing necessary packages...
      - sudo apt-get update
      - sudo apt-get install -y apache2 \
                 ghostscript \
                 libapache2-mod-php \
                 mysql-server \
                 php \
                 php-bcmath \
                 php-curl \
                 php-imagick \
                 php-intl \
                 php-json \
                 php-mbstring \
                 php-mysql \
                 php-xml \
                 php-zip
      - echo Installing Composer...
      - curl -sS https://getcomposer.org/installer | php
      - sudo mv composer.phar /usr/local/bin/composer
      - echo Installing PHP dependencies...
      - sudo composer install --no-dev
      - echo Creating WordPress directory...
      - sudo mkdir -p /srv/www
      - sudo chown -R www-data:www-data /srv/www
      - echo Downloading and extracting WordPress...
      - curl -o latest.tar.gz https://wordpress.org/latest.tar.gz
      - sudo -u www-data tar -zx -C /srv/www --strip-components=1 -f
        latest.tar.gz
      - rm latest.tar.gz
      - echo Configuring Apache for WordPress...
      - echo "<VirtualHost *:80>
      - DocumentRoot /srv/www <Directory /srv/www> Options FollowSymLinks
        AllowOverride Limit Options FileInfo DirectoryIndex index.php Require
        all granted </Directory> <Directory /srv/www/wp-content> Options
        FollowSymLinks Require all granted </Directory> </VirtualHost>" | sudo
        tee /etc/apache2/sites-available/wordpress.conf
      - sudo a2ensite wordpress
      - sudo a2enmod rewrite
      - sudo systemctl daemon-reload
      - sudo a2dissite 000-default
      - sudo service apache2 reload
  build:
    commands:
      - echo Build phase complete.
  post_build:
    commands:
      - echo "Configuring WordPress wp-config.php..."
      - RDS_HOST="database-3.ctqy8yuk4ky9.eu-north-1.rds.amazonaws.com"
      - RDS_DB_NAME="wordpress"
      - RDS_USER="admin"
      - RDS_PASSWORD="12345678"
      - WP_CONFIG_FILE="/srv/www/wp-config.php"
      - echo "Copying wp-config-sample.php to wp-config.php..."
      - sudo -u www-data cp /srv/www/wp-config-sample.php /srv/www/wp-config.php
      - echo "Updating wp-config.php with database credentials..."
      - sudo -u www-data sed -i "s/database_name_here/$RDS_DB_NAME/"
        /srv/www/wp-config.php
      - sudo -u www-data sed -i "s/username_here/$RDS_USER/"
        /srv/www/wp-config.php
      - sudo -u www-data sed -i "s/password_here/$RDS_PASSWORD/"
        /srv/www/wp-config.php
      - sudo -u www-data sed -i "s/localhost/$RDS_HOST/" /srv/www/wp-config.php
      - echo "Adding authentication keys to wp-config.php..."
      - AUTH_KEYS="$(curl -s https://api.wordpress.org/secret-key/1.1/salt/)"
      - echo "$AUTH_KEYS" | sudo tee -a $WP_CONFIG_FILE
     
artifacts:
  files:
    - "**/*"
  base-directory: /srv/www
